### ISSUE TITLE
Why did you say it's not safe?

### ISSUE THREAD

**Issue by templexxx** [tmthrgd/atomic128#1]
I saw your warning in README, but I wonder why?

Thank you!

**Comment by tmthrgd** [comment]
That’s a good question actually, I can’t remember why. I wrote this years ago strictly as an experiment so saying it’s not safe was probably just me being overly cautious.

I really can’t offer any guarantees this will still work (or even that it worked then), but I don’t see any real reason why it would be unsafe.

**Comment by templexxx** [comment]
> That’s a good question actually, I can’t remember why. I wrote this years ago strictly as an experiment so saying it’s not safe was probably just me being overly cautious.
> 
> I really can’t offer any guarantees this will still work (or even that it worked then), but I don’t see any real reason why it would be unsafe.

Thank you for your reply !

I've checked your code roughly, it's pretty and I found nothing wrong either.

The only issue may cause problem is that maybe you should check CMPXCHG16B feature before using it.

Because I'm doing the same job as you did here, thanks for your contribution, and there is a Go lib (wrote by me) could detect CMPXCHG16B feature, [here](https://github.com/templexxx/cpu)

**Comment by templexxx** [comment]
@tmthrgd 

And the memory address should be aligned to 16bytes

**Comment by tmthrgd** [comment]
> I've checked your code roughly, it's pretty and I found nothing wrong either.

That’s very kind of you.

> The only issue may cause problem is that maybe you should check CMPXCHG16B feature before using it.

That could absolutely be what I’d meant by not safe. I don’t know if it’s possible to provide the right semantics without that instruction though.

As it was just an experiment I’m unlikely to make any further changes to this code. Feel entirely free to fork it or incorporate it in a project however the license allows.
